############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About me"
url = "/about"
weight = 2

[[main]]
name = "CV"
url = "/cv"
weight = 3

[[main]]
name = "Blog"
url = "/blog"
weight = 4

# [[main]]
# parent = "Pages"
# name = "Contact"
# url = "/contact"
# 
# [[main]]
# parent = "Pages"
# name = "Authors"
# url = "/authors"
# 
# [[main]]
# parent = "Pages"
# name = "Categories"
# url = "/categories"
# 
# [[main]]
# parent = "Pages"
# name = "404 Page"
# url = "/404"


# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Blog"
url = "/blog"
weight = 2

# [[footer]]
# name = "Privacy Policy"
# url = "/privacy-policy"
# weight = 3
